### ISSUE TITLE
Typing issues in python 3.8.6 (broken?)

### ISSUE THREAD

**Issue by kratsg** [henryiii/uproot-browser#25]
Quick reproduction:

```
docker run -it --rm python:3.8 bash -c 'pip install --quiet uproot-browser; curl -sLO https://github.com/scikit-hep/scikit-hep-testdata/raw/main/src/skhep_testdata/data/uproot-issue213.root; uproot-browser browse uproot-issue213.root'
```

Would have expect this to work out of the box, but seems to be broken with this (very unhelpful) stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/uproot-browser", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uproot_browser/__main__.py", line 74, in browse
    import uproot_browser.tui  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.8/site-packages/uproot_browser/tui.py", line 14, in <module>
    from .tree_view import TreeView, UprootClick
  File "/usr/local/lib/python3.8/site-packages/uproot_browser/tree_view.py", line 15, in <module>
    from .tree import UprootItem
  File "/usr/local/lib/python3.8/site-packages/uproot_browser/tree.py", line 82, in <module>
    def _process_item_tfile(
  File "/usr/local/lib/python3.8/functools.py", line 858, in register
    argname, cls = next(iter(get_type_hints(func).items()))
  File "/usr/local/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/local/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/local/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

**Comment by kratsg** [comment]
Note, this works

```
docker run -it --rm python:3.9 bash -c 'pip install --quiet uproot-browser; curl -sLO https://github.com/scikit-hep/scikit-hep-testdata/raw/main/src/skhep_testdata/data/uproot-issue213.root; uproot-browser browse uproot-issue213.root'
```

**Comment by henryiii** [comment]
Yeah, we are using runtime type annotations in a few places and those need to be valid at runtime. I think we’ll need `--keep-runtime-typing` on pyupgrade and we’ll need valid runtime typing on the singe dispatch overloads.

**Comment by henryiii** [comment]
plot.py is okay but tree.py needs Thr typing classes.

**Comment by kratsg** [comment]
> Yeah, we are using runtime type annotations in a few places and those need to be valid at runtime. I think we’ll need `--keep-runtime-typing` on pyupgrade and we’ll need valid runtime typing on the singe dispatch overloads.

Do you have an example of what this means? I'm still a newbie with typing. What caused the code to crash here?

**Comment by henryiii** [comment]
Fixed in 0.3.1.

**Comment by henryiii** [comment]
`get_type_hints` is what's failing. Hmm, must be a missing `type[` -> `Type[`...

**Comment by henryiii** [comment]
Yeah, I fixed plot, but not tree. Tests would be really nice for this.
